# ApplicationSet.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ai-stack-generator
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/Minhajms/helm-chart-n8n-argocd.git
      revision: main
      directories:
      - path: "helm_charts/*"
  template:
    metadata:
      name: '{{path.basename}}-application'
    spec:
      project: default
      source:
        repoURL: https://github.com/Minhajms/helm-chart-n8n-argocd.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-namespace'
      ignoreDifferences:
      - group: "*"
        kind: "*"
        jsonPointers:
        - /metadata/namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true