# ApplicationSet.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ai-stack-generator
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/Minhajms/helm-chart-n8n-argocd.git
          revision: main
          directories:
          - path: "helm_charts/*"
      - list:
          elements:
          - env: prod
            valueFile: values.yaml
          - env: dev
            valueFile: dev-values.yaml
  template:
    metadata:
      name: '{{path.basename}}-{{env}}-application'
    spec:
      project: default
      source:
        repoURL: https://github.com/Minhajms/helm-chart-n8n-argocd.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
          - '{{valueFile}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-{{env}}-namespace'
      ignoreDifferences:
      - group: "*"
        kind: "*"
        jsonPointers:
        - /metadata/namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - IgnoreMissingValueFiles=true