# n8n-mysql-applicationset.yaml

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: n8n-stack-generator # Descriptive name for this ApplicationSet
  namespace: argocd # ApplicationSets must live in the argocd namespace
spec:
  generators:
  - git:
      repoURL: https://github.com/Minhajms/helm-chart-n8n-argocd.git
      revision: main
      directories:
      - path: "helm_charts/*"
        exclude: "helm_charts/*/*"
  template:
    metadata:
      name: '{{path.basename}}-application' # Generated Argo CD Application names (e.g., 'mysqlforn8n-application', 'n8n-helm-application')
    spec:
      project: default
      source:
        repoURL: https://github.com/Minhajms/helm-chart-n8n-argocd.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
          - values.yaml # Use only the primary values.yaml to avoid sub-chart conflicts
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-namespace'
      ignoreDifferences:
      - group: "*"
        kind: "*"
        jsonPointers:
        - /metadata/namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true # Ensure the namespace is created if it doesn't exist
  syncPolicy:
    applicationsSync: create-update
