# General configuration
replicaCount: 1

# MySQL Authentication
auth:
  rootPassword: "dummy-mysql-root-password" # <-- DUMMY: CHANGE THIS IN K8S SECRET LATER!
  username: "n8nuser"                        # User for n8n to connect
  password: "dummy-n8n-db-password"          # <-- DUMMY: CHANGE THIS IN K8S SECRET LATER!
  database: "n8n_database"                   # Database name for n8n

# Service configuration
service:
  type: ClusterIP # Internal access for n8n
  port: 3306

# Persistence for MySQL data
persistence:
  enabled: true
  storageClass: "standard"  # Minikube default StorageClass
  size: 5Gi                 # Sufficient for n8n's database
  accessModes:
    - ReadWriteOnce

# Resource requests and limits for MySQL pod
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi

# Tolerations to allow deployment on the master node (optional for Minikube)
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

# Node Selector (optional, for targeting specific nodes)
nodeSelector: {}

# Affinity rules (optional)
affinity: {}

# Password Update Job configuration
passwordUpdateJob:
  enabled: false

# Fix for nil pointer issue in template
primary:
  service:
    headless:
      annotations: {}     # <-- Prevents .annotations nil pointer error
    annotations: {}       # <-- Optional, if used in other service templates
    ports:
      mysql: 3306
  containerPorts:
    mysql: 3306            # <-- This is necessary for template compatibility
