# helm_charts/n8n-helm/values.yaml

n8n:
  encryption_key:

defaults:

config:
  executions:
    pruneData: "true"
    pruneDataMaxAge: 3760

  database:
    type: mysqldb
    mysqldb:
      host: mysql-for-n8n
      database: "n8n_database"
      port: 3306
      user: "n8nuser"

database:
  type: mysqldb
  tablePrefix:
  mysqldb:
    host: mysql-for-n8n
    database: "n8n_database"
    port: 3306
    user: "n8nuser"

credentials:
  overwrite:
    data:
    endpoint:

executions:
  process: own
  timeout: -1
  maxTimeout: 3600
  saveDataOnError: all
  saveDataOnSuccess: all
  saveDataManualExecutions: false
  pruneData: "true"
  pruneDataMaxAge: 3760
  pruneDataTimeout: 3600

generic:
  timezone: Asia/Kolkata

path: /
host: localhost
port: 5678
listen_address: 0.0.0.0
protocol: http
ssl_key:
ssl_cert:

security:
  excludeEndpoints:
  basicAuth:
    active: false
    user:
    password:
    hash: false
  jwtAuth:
    active: false
    jwtHeader:
    jwtHeaderValuePrefix:
    jwksUri:
    jwtIssuer:
    jwtNamespace:
    jwtAllowedTenantKey:
    jwtAllowedTenant:

endpoints:
  rest: rest
  webhook: webhook
  webhookTest: webhook-test
  webhookWaiting: webhook-waiting

externalHookFiles:
nodes:
  exclude: "[]"
  errorTriggerType: n8n-nodes-base.errorTriggerType

extraEnv:
  DB_TYPE: "mysqldb"
  DB_MYSQLDB_HOST: "mysql-for-n8n"
  DB_MYSQLDB_PORT: "3306"
  DB_MYSQLDB_DATABASE: "n8n_database"
  DB_MYSQLDB_USER: "n8nuser"
  DB_MYSQLDB_PASSWORD: "dummy-n8n-db-password"
  # WEBHOOK_URL: "https://n8n.yourdomain.com/"

extraEnvSecrets: {}

persistence:
  enabled: true
  type: dynamic
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 1Gi

replicaCount: 1

deploymentStrategy:
  type: "Recreate"

image:
  repository: n8nio/n8n
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
lifecycle: {}
command: []

livenessProbe:
  httpGet:
    path: /
    port: 5678
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /
    port: 5678
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 5

initContainers: []

service:
  type: ClusterIP
  port: 80
  annotations: {}

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  className: ""

workerResources: {}
webhookResources: {}

resources:
  requests:
    cpu: 600m
    memory: 1Gi
  limits:
    cpu: 1.5
    memory: 2Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity: {}

scaling:
  enabled: false
  worker:
    count: 2
    concurrency: 2
  webhook:
    enabled: false
    count: 1
  redis:
    host:
    password:

redis:
  enabled: false
  architecture: standalone
  master:
    persistence:
      enabled: true
      existingClaim: ""
      size: 2Gi
